name: Vilson Vieira
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.80702
title: Vilson Vieira
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#7b7070"
    - "#a4a4a4"
    - "#5b5252"
    - "#8d8686"
    - "#e9e9e9"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
